-- 코드를 입력하세요
# MAX가 1개면 이게 맞음
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") DATE
FROM MEMBER_PROFILE M
INNER JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1)
ORDER BY DATE, REVIEW_TEXT

# MAX가 여러개면 이게 맞음
# SELECT MID.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") DATE
# FROM REST_REVIEW R
# RIGHT JOIN
# (SELECT M.MEMBER_NAME, MAX_ID.MEMBER_ID
# FROM MEMBER_PROFILE M
# RIGHT JOIN (SELECT MEMBER_ID, COUNT(*) CNT
# FROM REST_REVIEW
# GROUP BY MEMBER_ID
# HAVING CNT = (SELECT MAX(C) FROM (SELECT COUNT(*) C
# FROM REST_REVIEW
# GROUP BY MEMBER_ID) A)) MAX_ID
# ON M.MEMBER_ID = MAX_ID.MEMBER_ID) MID
# ON R.MEMBER_ID = MID.MEMBER_ID
# ORDER BY DATE, R.REVIEW_TEXT