-- 코드를 입력하세요
WITH RECURSIVE PR AS(
    SELECT 0 AS PRICE
    UNION ALL
    SELECT PRICE + 10000 FROM PR WHERE PRICE < 100000)

SELECT PR.PRICE, COUNT(PRODUCT.PRICE)
FROM PR
RIGHT JOIN PRODUCT
ON PRODUCT.PRICE < PR.PRICE + 10000 AND PRODUCT.PRICE >= PR.PRICE
GROUP BY PR.PRICE
ORDER BY PRICE;